#!/bin/sh
now_month=$(date +%Y_%m)
today=$(date +%Y_%m_%d)
echo "今日学んだこと" >> /Users/nagatadaichi/til/term/$now_month/$today.md
git add /Users/nagatadaichi/til/term/$now_month/$today.md
git commit -m "$today _add_title"